name: Update update.sh

on: [push]
jobs:
  Update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run update.sh
        shell: bash
        working-directory: ${{github.workspace}}
        run: ./update.sh
